import scala.collection.parallel.immutable.ParSeq

/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
class Library {

  def addConstantNumberParallel(constantNumber: Int, numberList: List[Int]): ParSeq[Int] = {
    numberList.par.map(number => number + constantNumber)
  }

  def addConstantNumber(constantNumber: Int, numberList: List[Int]): List[Int] = {
    numberList.map(number => number + constantNumber)
  }

  def someLibraryMethod(): Boolean = true
}
